### ISSUE TITLE
Request: add freshdrops

### ISSUE THREAD

**Issue by cap10bad** [SYNC-Network/collectionlists-org#1]
**YOU MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/SYNC-Network/collection-lists

Checklist
- [x] **I understand that this is not the place to request NFT Project/Token/Collection listing.**
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `neonrain.io`.
- [x] I understand that filing an issue or being on a different platform does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List URL: https://freshdrops.io/list
List Name: freshdrops
Link to the official homepage of the list manager: https://freshdrops.io

**Comment by CRYPTO-GENIK** [comment]
Done!
